### ISSUE TITLE
'AudioItem' object has no attribute 'reconstruct' when calling `audio_predict`

### ISSUE THREAD

**Issue by tbass134** [fastaudio/fastai_audio#17]
I'm running the Getting Started notebook and was looking into making predictions, however when calling audio_predict function
`preds = audio_predict(learn, data_folder.ls()[500])
preds`
I receive the error:
AttributeError: 'AudioItem' object has no attribute 'reconstruct'

The notebook that shows the error is here:
https://colab.research.google.com/drive/17PoFqEH90DNfVUiIMuOBQu0HO9bkN0jh

Any info on this would be appreciated

**Comment by mogwai** [comment]
Should be fixed by #20

**Comment by tbass134** [comment]
Thanks, It looks like #22  fixed this issue.
