### ISSUE TITLE
**NameError: name 'cnn_learner' is not defined**

### ISSUE THREAD

**Issue by AIClaire** [fastaudio/fastai_audio#24]
Hello,

I am having an issue with the recent update in fastai impacting fastai_audio.

When I try to run my learner it posts the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-69-8bd26bdb8010> in <module>
----> 1 learn = audio_learner(db)
      2 learn.lr_find()
      3 learn.recorder.plot()

~/course-v3/nbs/audio/learner.py in audio_learner(data, base_arch, metrics, **kwargs)
      4 def audio_learner(data:DataBunch, base_arch:Callable=models.resnet18, metrics=accuracy, **kwargs):
      5     '''Wrapper function for fastai learner. Converts head of model to fit one channel input.'''
----> 6     return cnn_learner(data, base_arch, metrics=metrics, **kwargs)
      7 
      8 def audio_predict(learn, item:AudioItem):

**NameError: name 'cnn_learner' is not defined**

Is there an update I can pull to fix this?

Thanks!

Claire

**Comment by mogwai** [comment]
What version of fastai are you using? How are you importing the audio module?

**Comment by AIClaire** [comment]
Hello - sorry for the delay - 1.0.45

I imported following the instructions on your first page.

**Comment by AIClaire** [comment]
Updated version of fastai and pytorch audio which fixed issue - sorry!
