### ISSUE TITLE
Using very specific torchaudio from May 24th

### ISSUE THREAD

**Issue by kevinbird15** [fastaudio/fastai_audio#29]
https://github.com/mogwai/fastai_audio/blob/e8499b72876292b5013f2382a7eef7317aa674e8/install.sh#L9

I'm concerned about using this specific of a torchaudio version especially since it is from May.  Is there a better way to handle this?  I'm running into an issue currently that I've narrowed down to a torchaudio file, but I don't know if it's something that will be fixed when I upgrade to a newer version or not.

**Comment by mogwai** [comment]
Torch audio is still under development. This is the version that we know works. What is the issue your facing we could upgrade it.

**Comment by kevinbird15** [comment]
I'm creating a remove silence processor and some of my audio files are 0 bytes so when I try to open the 0 byte files, it crashes jupyter notebook. In later versions it appears to be fixed, but I changed multiple things so I can't really say if getting a newer version of torchaudio was they key or if it was something else.

**Comment by rbracco** [comment]
Closing this issue as we are migrating to torchaudio 0.3.0 as discussed in Issue #37
