### ISSUE TITLE
ipy_audio returns incorrect time

### ISSUE THREAD

**Issue by kevinbird15** [fastaudio/fastai_audio#36]
On the first load, ipy_audio returns the incorrect time.  If you re-run the cell, it looks correct.  I haven't had any luck tracking this error down, but it's definitely consistent on my end at least.  

To reproduce:
1. Load an Audio file as an AudioItem
1. run `audio_item.ipy_audio` observe the output
1. rerun `audio_item.ipy_audio` in the next cell and the time will be correct

![image](https://user-images.githubusercontent.com/7451178/63073566-001ef200-beef-11e9-8bc1-1d747e910880.png)

**Comment by mogwai** [comment]
What browser is this on?

**Comment by kevinbird15** [comment]
Chrome, I can get version later. Is this not a fastai_audio problem but a problem with how the audio html tags work?

**Comment by rbracco** [comment]
I tried and am unable to replicate. My attempt was using the Getting Started notebook, and after splitting/labeling here: 

`audios = AudioList.from_folder(data_folder, config=config).split_by_rand_pct(.2, seed=4).label_from_re(label_pattern)` 

running 

`audios.train.x[0]` multiple times. I found no differences and haven't seen this problem before. Am I properly replicating?

**Comment by kevinbird15** [comment]
Looks correct to me.  It must be something with my specific environment.

**Comment by kevinbird15** [comment]
Actually this is on firefox.  I forgot I had transitioned.

**Comment by mogwai** [comment]
Yes this is an issue with firefox. Use chrome to avoid this
