### ISSUE TITLE
resampling, removing silence, and segmenting items takes 3x cache 

### ISSUE THREAD

**Issue by kevinbird15** [fastaudio/fastai_audio#39]
I realized today that resample_to, remove_silence, and segment_size will all build their own unique caches.  This is because of how they currently go through one at a time.  I believe this is something that could be cleaned up and will need to be less storage intensive for it to be more widely utilized.  Currently just want to get ideas around how we would do this without such a large cache requirement.  I'm thinking we could maybe wait to build the cache until the end of those if statements but if that's the case it may also require doing the preprocessing in batches so that things can be as efficient as possible.

**Comment by mogwai** [comment]
Definitely agree about this. I will look into caching vs gpu transforms for the v2 version of the libarary.
