### ISSUE TITLE
stat: path should be string, bytes, os.PathLike or integer, not AudioItem

### ISSUE THREAD

**Issue by terranivium** [fastaudio/fastai_audio#65]
Occurs when attempting to run preds on the getting started notebook, TypeError: stat: path should be string, bytes, os.PathLike or integer, not AudioItem.

**Comment by mogwai** [comment]
We've had a few issues with the prediction parts of the library. I'll look into what is going on here.

**Comment by mogwai** [comment]
Should be fixed in #68
